.github/template-cleanup/gradle.properties

Using template overwrites `gradle.properties`, cleanup makes plugin unusable in current platform

Bump pluginUntilBuild to 202.* in template cleanup

---

.github/workflows/build.yml

This PR adds caching Gradle wrapper directory in GitHub Actions.
Updating `actions/cache` to v2 allows to cache multiple paths. So now we can cache Gradle wrapper directory and avoid downloading it every time.
Official Gradle example: https://github.com/actions/cache/blob/main/examples.md#java---gradle

chore: cache gradle wrapper directory

---

.github/workflows/template-cleanup.yml

`ad-m/github-push-action` defaults to pushing `HEAD` to `master`, but we want it to go to `main` now

Push template cleanup commit to correct branch

---

.github/workflows/release.yml

Changelog commits should be pushed to the `main` branch, the Github action defaults to `master` still.
Similar to #31 -- sorry I missed this case!

Use `main` branch for changelog commit push

---

.github/workflows/build.yml

If a project has a different project name in gradle and in the intellij plugin, the build will now fail, since the `pluginName_` bug was fixed.
This change targets the correct property, now that they can potentially diverge in some projects.

Fix artifact name grep pattern

---

.github/workflows/build.yml
.github/workflows/release.yml

The docker container `gradle:jdk8` uses Git 2.17 which causes the checkout action to clone the repo via HTTP instead of creating a local git repo. This breaks the changelog auto commit, since there's no local repo to commit to.
Example of this failure: https://github.com/nbadal/ktlint-intellij-plugin/runs/1119530857
This can be verified as well by running the following, locally:
`docker run --rm gradle:jdk8 git --version`
This change switches back to the Github-hosted action containers, which are going to be more up-to-date anyway than any other custom container, at the expense of adding back the Java setup action.

Switch back to using Github containers to fix changelog commit

---

src/main/resources/META-INF/plugin.xml

Hi! 
I'm creating a plugin and started from this template, but had trouble showing a simple message. The logs indicated my plugin was loading correctly but on the UI nothing happened. After spending some time trying various things, I took a look at the code samples and didn't find any `<projectListeners>` like the one in the template. I only found `<applicationListeners>`, so I tried replacing `<projectListeners>` with it and everything worked.
Apparently, listeners for topic `com.intellij.openapi.project.ProjectManagerListener` don't work inside `<projectListeners>`, only `<applicationListeners>`.

Fix ProjectManagerListener scope

---

.github/template-cleanup/gradle.properties
CHANGELOG.md

After the template cleanup has ran, the following properties are not there anymore.
So I just added them to the cleanup gradle.properties, so user's can see that this is some options which is supported.

Add missing gradle.properties values to cleanup

---

CHANGELOG.md
detekt-config.yml

The default detekt configuration for continuation indent is 4, what conflicts with the default configuration in IJ. I suggest updating detekt configuration to have the same continuation indent as in IJ.
`ParameterListWrapping` option is updated as well because it's covered by "continuation indent" option in IJ.
Example of code with continuation indent:
Example of `ParameterListWrapping` code:

Update detekt config to be in line with IJ settings

---

CHANGELOG.md
src/main/kotlin/org/jetbrains/plugins/template/listeners/MyProjectManagerListener.kt

As show in the [documentation](https://jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_services.html?search=servic#retrieving-a-service), a convenience method is available to retrieve services.
This PR changes the "Java-style" service retrieval in `MyProjectManagerListener` to the Kotlin extension function.
I think it is a nice way to make developers aware of its existence (I was very happy to refactor to this approach when I found out the function existed 😉 ).

Use Kotlin extension function to retrieve service

---

.run/Run IDE with Plugin.run.xml
.run/Run Plugin Tests.run.xml
.run/Run Plugin Verification.run.xml

Added to the 3 predefined run configuration files. 
Tested it by creating from the template a new repository and running all the 3 run configuraitons. 
In the runIde and in the check tasks I saw there were some printing in the idea.log while in tests there were not so I am not sure about the need in it.

Adding log_file in the predefined run configuration files

---

src/main/kotlin/org/jetbrains/plugins/template/MyBundle.kt

I believe `run { message() }` was a typo there - it would just return a string, similar to `message`.
Returning `Supplier` is not idiomatic Kotlin, but it:
- Allows annotating type parameter with `@Nls`
- Is similar to most in-tree IJ bundles

Fix `MyBundle.messagePointer` to return `Supplier<@Nls String>` instead of `String`

---

.github/workflows/build.yml
CHANGELOG.md

The `needs.build` accessor is only available in downstream jobs that depend on the `build` job.
For steps that are part of the same job, the `needs.build.outputs.artifact` property is empty.

Use the correct property in the "Upload artifact" step

---

build.gradle.kts

It fixes **null** value instead of actual plugin version.
You could find the problem in draft release name.

Fixed plugin version property key

---

.github/dependabot.yml
CHANGELOG.md

https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

Update dependabot configuration to also track github actions dependencies

---

build.gradle.kts

In some build environments projectDir may differ from current working directory. In such environments build before this change would fail with IOException.

Fix README.md resolution

---

.github/workflows/build.yml

Qodana action has been released and it has no longer 'eap' postfix

update qodana action

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md

By default [`GITHUB_TOKEN` has `read` access to `contents` scope](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) which includes releases. Because of that the template fails to create draft releases with an error like that:
```console
gh release create v0.1.0 \
...
HTTP 403: Resource not accessible by integration (https://api.github.com/repos/bufbuild/intellij-buf/releases)
```
This change explicitly sets permissions for release related jobs.

Make sure GHA release jobs have permissions

---

.github/workflows/release.yml

Actually, when releasing a new version, the `release.yml` fails to create a pull request with error:
```
pull request create failed: GraphQL: Resource not accessible by integration (createPullRequest)
```
We can add the `write` permissions into Github Actions to enable it.

fix: update permissions to write pull-requests

---

README.md

The path in readme was incorrect.
See https://github.com/JetBrains/intellij-platform-plugin-template/tree/main/src/test

Fix wrong path in readme

---

.github/workflows/build.yml
.github/workflows/release.yml
CHANGELOG.md

Github Actions `::set-output` command is deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ and should be replaced with `GITHUB_OUTPUT` environment file.

Remove github-actions ::set-output command.

---

.github/workflows/release.yml

Hey 👋 Amazing work with this template!
Got a little bit stuck during publishing, cause it seems that only `PUBLISH_TOKEN` is required.

Clearer comment for .github/workflows/release.yml

---

build.gradle.kts

Using the provider API defers configuration work until it is needed, reducing configuration time. Furthermore, it is required for making the build configuration cache compatible.

Migrate to provider API improving configuration cache compatibility

---

.github/workflows/build.yml

Closes https://github.com/JetBrains/intellij-platform-plugin-template/issues/339

Pass the cache folder to `runPluginVerifier` correctly

---

CHANGELOG.md
settings.gradle.kts

This is needed for toolchains to work

(🎁) Add Foojay toolchain provider plugin

---

.github/template-cleanup/gradle.properties
CHANGELOG.md
gradle.properties

Remove Gradle Kotlin DSL Lazy Property Assignment

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/run-ui-tests.yml

Replaces gradle-build-action renamed to actions/setup-gradle as specified in https://github.com/gradle/gradle-build-action/releases/tag/v3.0.0 to fix warning:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: gradle/gradle-build-action@v2`

GitHub Actions: Replace gradle/gradle-build-action@v2 with gradle/actions/setup-gradle@v3

---

.github/template-cleanup/settings.gradle.kts
CHANGELOG.md
settings.gradle.kts

Is dependabot broken????? (#439, [comment](https://github.com/JetBrains/intellij-platform-plugin-template/issues/435#issuecomment-1954895020))

(🎁) Bump org.gradle.toolchains.foojay-resolver-convention

---

.github/template-cleanup/settings.gradle.kts
.github/workflows/build.yml
CHANGELOG.md
build.gradle.kts
settings.gradle.kts

Before this patch, publisher was always using the channel corresponding to the first number in the plugin version for release builds. This is because by default, Kotlin's `substringAfter` will return the whole input string if it's unable to find the needle.
So, for example, `"1.2.3".substringAfter('-').substringBefore('.')` would yield `"1"`.

Plugin publication: fix the channel selector

---

.github/template-cleanup/README.md

Currently the README suggests that the links / badges should point to `https://plugins.jetbrains.com/plugin/PLUGIN_ID` where `PLUGIN_ID` is the value from the `id` field in the `plugin.xml`. 
This is not correct, as the Marketplace listing has its own ID which can be obtained once the plugin was published.

README: clarify which id should be used for the badges

---

.github/template-cleanup/README.md

Since the marketplace does provide a convenient method to install plugins into a running IDE as well as downloading the latest version it should be mentioned in the README.
On a side-note: I was tempted to remove the "Manually" option that references the GitHub Releases. I would think that it may become an issue in case a plugin release was pushed to GitHub but is still awaiting verification for the marketplace. This does not only create a mismatch between those two sources but may also impose further issues in case the verification is not succesful and the version is being revoked. Idealy the README would only propose the "prefered" or "official" ways of obtaining a plugin - which would be the marketplace I guess.

README: add marketplace as installation option

---

settings.gradle.kts

The `build.gradle.kts` defines a JVM toolchain, but if no compatible JDK is found, no JDK is downloaded and the build fails.  
To download a JDK automatically if needed, we need the `org.gradle.toolchains.foojay-resolver-convention` plugin. Tested on Arch Linux, with JDK21 installed: after adding the foojay plugin, `./gradlew buildPlugin` no longer fails, and it downloads a compatible JDK17.

fix JVM toolchain download

---

.github/workflows/build.yml

This step is no longer necessary, as setup-gradle@v4 [will now handle the same wrapper validation](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#gradle-wrapper-validation).
From the [Build action log](https://github.com/JetBrains/intellij-platform-plugin-template/actions/runs/12324116118/job/34401040534?pr=491) of this PR without wrapper-validation:
```
All Gradle Wrapper jars are valid
✓ Found known Gradle Wrapper JAR files:
2db75c40782f5e8ba1fc278a5574bab070adccb2d21ca5a6e5ed840888448046 gradle/wrapper/gradle-wrapper.jar
```

GitHub Actions: Remove gradle/actions/wrapper-validation because validation is performed by default in gradle/actions/setup-gradle@v4

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/run-ui-tests.yml

Github actions' java-version should also be updated in continuation with https://github.com/JetBrains/intellij-platform-plugin-template/commit/492fd44e346f15b919b3beee77cabf45f6c6c7a6

chore(github-actions): bump java-version

---

settings.gradle.kts

https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention
I guess Dependabot doesn't see this? Or maybe [the ignore](https://github.com/JetBrains/intellij-platform-plugin-template/pull/402#issuecomment-1695446543) was too strong.

Dependencies - upgrade org.gradle.toolchains.foojay-resolver-convention to 0.10.0

---

README.md

This update improves the Continuous Integration (CI) documentation by adding a note on configuring GitHub Actions permissions. Without the specified "Read and write permissions" setting, attempts to execute the "Create Pull Request" step in the "Publish Plugin" job may fail, causing the following error:
```
2024-11-04T14:54:19.0941876Z Switched to a new branch 'changelog-update-v1.4.0'
2024-11-04T14:54:19.1052147Z [changelog-update-v1.4.0 099822b] Changelog update - v1.4.0
2024-11-04T14:54:19.1053680Z  1 file changed, 42 insertions(+), 12 deletions(-)
2024-11-04T14:54:19.6046236Z To https://github.com/siropkin/kursor
2024-11-04T14:54:19.6050386Z  ! [remote rejected] changelog-update-v1.4.0 -> changelog-update-v1.4.0 (refusing to allow a GitHub App to create or update workflow …
```

README: Update Continuous Integration section with note on setting GitHub Actions permissions
